import type { PublishedSchema } from '#types'

type Node = {
  name: string
  children: Map<string, Node>
  path?: string
  arguments: Record<string, string>
}

export function generateDart(schema: PublishedSchema): string {
  const root = schemaTree(schema)
  const lines = [
    '// Generated by LinguaFlow. Do not edit.',
    "import 'package:linguaflow_sdk/linguaflow_sdk.dart';",
    '',
    'abstract final class Lf {',
    ...[...root.children.values()].map(rootMember),
    '}',
    '',
  ]
  for (const node of root.children.values()) {
    if (node.children.size) writeClass(lines, node, [node.name])
  }
  return `${lines.join('\n')}\n`
}

export function generateTypeScript(schema: PublishedSchema): string {
  const root = schemaTree(schema)
  const lines = [
    '// Generated by LinguaFlow. Do not edit.',
    "import { key, message } from '@linguaflow/react';",
    '',
    'export const lf = {',
  ]
  writeTypeScriptChildren(lines, root, 1)
  lines.push('} as const', '')
  return `${lines.join('\n')}\n`
}

export function generateSwift(schema: PublishedSchema): string {
  const root = schemaTree(schema)
  const lines = [
    '// Generated by LinguaFlow. Do not edit.',
    'import LinguaFlow',
    '',
    'public enum Lf {',
  ]
  writeSwiftChildren(lines, root, 1)
  lines.push('}', '')
  return `${lines.join('\n')}\n`
}

export function generateKotlin(schema: PublishedSchema): string {
  const root = schemaTree(schema)
  const lines = [
    '// Generated by LinguaFlow. Do not edit.',
    'package generated',
    '',
    'import dev.linguaflow.LfKey',
    'import dev.linguaflow.LfMessage',
    '',
    'object Lf {',
  ]
  writeKotlinChildren(lines, root, 1)
  lines.push('}', '')
  return `${lines.join('\n')}\n`
}

function schemaTree(schema: PublishedSchema): Node {
  const root = createNode('root')
  for (const key of [...schema.keys].sort()) {
    let cursor = root
    for (const segment of key.split('.')) {
      if (cursor.path) throw new Error(`Conflicting localization key: ${key}`)
      let child = cursor.children.get(segment)
      if (!child) {
        child = createNode(segment)
        cursor.children.set(segment, child)
      }
      cursor = child
    }
    if (cursor.children.size || cursor.path) throw new Error(`Conflicting localization key: ${key}`)
    cursor.path = key
    cursor.arguments = schema.messages[key]?.arguments ?? {}
  }
  return root
}

function writeTypeScriptChildren(lines: string[], node: Node, depth: number): void {
  const indent = '  '.repeat(depth)
  for (const child of node.children.values()) {
    const name = jsIdentifier(child.name)
    if (child.children.size) {
      lines.push(`${indent}${name}: {`)
      writeTypeScriptChildren(lines, child, depth + 1)
      lines.push(`${indent}},`)
    } else if (!Object.keys(child.arguments).length) {
      lines.push(`${indent}${name}: key('${child.path}'),`)
    } else {
      const parameters = Object.entries(child.arguments)
        .map(([argument, kind]) => `${jsIdentifier(argument)}: ${typescriptType(kind)}`)
        .join(', ')
      const values = Object.keys(child.arguments).map(jsIdentifier).join(', ')
      lines.push(`${indent}${name}: (${parameters}) => message('${child.path}', { ${values} }),`)
    }
  }
}

function writeSwiftChildren(lines: string[], node: Node, depth: number): void {
  const indent = '  '.repeat(depth)
  for (const child of node.children.values()) {
    const name = swiftIdentifier(child.name)
    if (child.children.size) {
      lines.push(`${indent}public enum ${swiftType(child.name)} {`)
      writeSwiftChildren(lines, child, depth + 1)
      lines.push(`${indent}}`)
    } else if (!Object.keys(child.arguments).length) {
      lines.push(`${indent}public static let ${name} = LfKey("${child.path}")`)
    } else {
      const parameters = Object.entries(child.arguments)
        .map(([argument, kind]) => `${swiftIdentifier(argument)}: ${swiftValueType(kind)}`)
        .join(', ')
      const values = Object.entries(child.arguments)
        .map(
          ([argument, kind]) =>
            `"${argument}": .${swiftArgumentCase(kind)}(${swiftIdentifier(argument)})`,
        )
        .join(', ')
      lines.push(
        `${indent}public static func ${name}(${parameters}) -> LfMessage { LfMessage("${child.path}", [${values}]) }`,
      )
    }
  }
}

function writeKotlinChildren(lines: string[], node: Node, depth: number): void {
  const indent = '  '.repeat(depth)
  for (const child of node.children.values()) {
    const name = kotlinIdentifier(child.name)
    if (child.children.size) {
      lines.push(`${indent}object ${kotlinType(child.name)} {`)
      writeKotlinChildren(lines, child, depth + 1)
      lines.push(`${indent}}`)
    } else if (!Object.keys(child.arguments).length) {
      lines.push(`${indent}val ${name} = LfKey("${child.path}")`)
    } else {
      const parameters = Object.entries(child.arguments)
        .map(([argument, kind]) => `${kotlinIdentifier(argument)}: ${kotlinValueType(kind)}`)
        .join(', ')
      const values = Object.keys(child.arguments)
        .map((argument) => `"${argument}" to ${kotlinIdentifier(argument)}`)
        .join(', ')
      lines.push(
        `${indent}fun ${name}(${parameters}) = LfMessage("${child.path}", mapOf(${values}))`,
      )
    }
  }
}

function writeClass(lines: string[], node: Node, ancestry: string[]): void {
  const nested = [...node.children.values()].filter((child) => child.children.size > 0)
  const currentClass = ancestry.map(className).join('')
  const initializer = nested.length
    ? ` : ${nested
        .map(
          (child) =>
            `${identifier(child.name)} = const _${[...ancestry, child.name].map(className).join('')}Keys()`,
        )
        .join(', ')}`
    : ''
  lines.push(`class _${currentClass}Keys {`, `  const _${currentClass}Keys()${initializer};`)
  for (const child of node.children.values()) {
    const field = identifier(child.name)
    if (child.children.size === 0 && Object.keys(child.arguments).length === 0) {
      lines.push(`  final ${field} = const LfKey('${child.path}');`)
    } else if (child.children.size === 0) {
      const parameters = Object.entries(child.arguments)
        .map(([name, kind]) => `required ${dartType(kind)} ${identifier(name)}`)
        .join(', ')
      const values = Object.keys(child.arguments)
        .map((name) => `'${name}': ${identifier(name)}`)
        .join(', ')
      lines.push(
        `  LfMessage ${field}({${parameters}}) => LfMessage('${child.path}', {${values}});`,
      )
    } else {
      lines.push(`  final _${[...ancestry, child.name].map(className).join('')}Keys ${field};`)
    }
  }
  lines.push('}', '')
  for (const child of nested) writeClass(lines, child, [...ancestry, child.name])
}

function createNode(name: string): Node {
  return { name, children: new Map(), arguments: {} }
}

function rootMember(node: Node): string {
  const name = identifier(node.name)
  if (node.children.size) return `  static const ${name} = _${className(node.name)}Keys();`
  if (!Object.keys(node.arguments).length) return `  static const ${name} = LfKey('${node.path}');`
  const parameters = Object.entries(node.arguments)
    .map(([argument, kind]) => `required ${dartType(kind)} ${identifier(argument)}`)
    .join(', ')
  const values = Object.keys(node.arguments)
    .map((argument) => `'${argument}': ${identifier(argument)}`)
    .join(', ')
  return `  static LfMessage ${name}({${parameters}}) => LfMessage('${node.path}', {${values}});`
}

function className(value: string): string {
  return value
    .split('_')
    .map((part) => (part ? `${part[0]!.toUpperCase()}${part.slice(1)}` : ''))
    .join('')
}

function identifier(value: string): string {
  const safe = value.replaceAll(/[^a-zA-Z0-9_]/g, '_')
  return /^\d/.test(safe) || dartReserved.has(safe) ? `k_${safe}` : safe
}

const dartReserved = new Set([
  'abstract',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'default',
  'deferred',
  'do',
  'dynamic',
  'else',
  'enum',
  'export',
  'extends',
  'extension',
  'external',
  'factory',
  'false',
  'final',
  'finally',
  'for',
  'function',
  'get',
  'hide',
  'if',
  'implements',
  'import',
  'in',
  'interface',
  'is',
  'late',
  'library',
  'mixin',
  'new',
  'null',
  'on',
  'operator',
  'part',
  'required',
  'rethrow',
  'return',
  'set',
  'show',
  'static',
  'super',
  'switch',
  'sync',
  'this',
  'throw',
  'true',
  'try',
  'typedef',
  'var',
  'void',
  'while',
  'with',
  'yield',
])

function dartType(kind: string): string {
  if (kind === 'number') return 'num'
  if (kind === 'date' || kind === 'time') return 'DateTime'
  return 'String'
}

function jsIdentifier(value: string): string {
  const safe = value.replaceAll(/[^a-zA-Z0-9_$]/g, '_')
  return /^[$A-Z_a-z][$\w]*$/.test(safe) && !jsReserved.has(safe) ? safe : `k_${safe}`
}

function swiftIdentifier(value: string): string {
  const safe = value.replaceAll(/[^a-zA-Z0-9_]/g, '_')
  const candidate = /^\d/.test(safe) ? `k_${safe}` : safe
  return swiftReserved.has(candidate) ? `k_${candidate}` : candidate
}

function kotlinIdentifier(value: string): string {
  const safe = value.replaceAll(/[^a-zA-Z0-9_]/g, '_')
  const candidate = /^\d/.test(safe) ? `k_${safe}` : safe
  return kotlinReserved.has(candidate) ? `k_${candidate}` : candidate
}

function swiftType(value: string): string {
  const name = className(value)
  return /^\d/.test(name) ? `K${name}` : name
}

function kotlinType(value: string): string {
  const name = className(value)
  return /^\d/.test(name) ? `K${name}` : name
}

function typescriptType(kind: string): string {
  return kind === 'number' ? 'number' : kind === 'date' || kind === 'time' ? 'Date' : 'string'
}

function swiftValueType(kind: string): string {
  return kind === 'number' ? 'Double' : kind === 'date' || kind === 'time' ? 'Date' : 'String'
}

function swiftArgumentCase(kind: string): string {
  if (kind === 'number') return 'number'
  if (kind === 'date' || kind === 'time') return 'date'
  return 'string'
}

function kotlinValueType(kind: string): string {
  return kind === 'number'
    ? 'Number'
    : kind === 'date' || kind === 'time'
      ? 'java.util.Date'
      : 'String'
}

const jsReserved = new Set([
  'break',
  'case',
  'catch',
  'class',
  'const',
  'default',
  'delete',
  'do',
  'else',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'import',
  'in',
  'instanceof',
  'let',
  'new',
  'null',
  'return',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield',
])
const swiftReserved = new Set([
  'class',
  'deinit',
  'enum',
  'extension',
  'func',
  'import',
  'init',
  'inout',
  'internal',
  'let',
  'operator',
  'private',
  'protocol',
  'public',
  'static',
  'struct',
  'subscript',
  'typealias',
  'var',
])
const kotlinReserved = new Set([
  'as',
  'break',
  'class',
  'continue',
  'do',
  'else',
  'false',
  'for',
  'fun',
  'if',
  'in',
  'interface',
  'is',
  'null',
  'object',
  'package',
  'return',
  'super',
  'this',
  'throw',
  'true',
  'try',
  'typealias',
  'typeof',
  'val',
  'var',
  'when',
  'while',
])
